run:
  timeout: 5m
  go: "1.24"

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - gosec
    - gocyclo
    - dupl
    - misspell
    - unparam
    - unconvert
    - goconst
    - gocritic
    - godot
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - scopelint
    - sqlclosecheck
    - stylecheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - wrapcheck

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  lll:
    line-length: 140
  goconst:
    min-len: 2
    min-occurrences: 3
  gomnd:
    checks: argument,case,condition,operation,return,assign
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - gocyclo
        - dupl
        - gocritic
    - path: proto/
      linters:
        - gomnd
        - gocritic
    - path: cmd/migrate/
      linters:
        - gomnd
        - gocritic
  max-issues-per-linter: 0
  max-same-issues: 0

