// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: order-svc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PurchaseResponse_Status int32

const (
	PurchaseResponse_QUEUED           PurchaseResponse_Status = 0
	PurchaseResponse_SOLD_OUT         PurchaseResponse_Status = 1
	PurchaseResponse_ALREADY_IN_QUEUE PurchaseResponse_Status = 2
	PurchaseResponse_ERROR            PurchaseResponse_Status = 3
	PurchaseResponse_QUEUE_FULL       PurchaseResponse_Status = 4
)

// Enum value maps for PurchaseResponse_Status.
var (
	PurchaseResponse_Status_name = map[int32]string{
		0: "QUEUED",
		1: "SOLD_OUT",
		2: "ALREADY_IN_QUEUE",
		3: "ERROR",
		4: "QUEUE_FULL",
	}
	PurchaseResponse_Status_value = map[string]int32{
		"QUEUED":           0,
		"SOLD_OUT":         1,
		"ALREADY_IN_QUEUE": 2,
		"ERROR":            3,
		"QUEUE_FULL":       4,
	}
)

func (x PurchaseResponse_Status) Enum() *PurchaseResponse_Status {
	p := new(PurchaseResponse_Status)
	*p = x
	return p
}

func (x PurchaseResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PurchaseResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_order_svc_proto_enumTypes[0].Descriptor()
}

func (PurchaseResponse_Status) Type() protoreflect.EnumType {
	return &file_order_svc_proto_enumTypes[0]
}

func (x PurchaseResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PurchaseResponse_Status.Descriptor instead.
func (PurchaseResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_order_svc_proto_rawDescGZIP(), []int{1, 0}
}

type PurchaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseRequest) Reset() {
	*x = PurchaseRequest{}
	mi := &file_order_svc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseRequest) ProtoMessage() {}

func (x *PurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_svc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseRequest.ProtoReflect.Descriptor instead.
func (*PurchaseRequest) Descriptor() ([]byte, []int) {
	return file_order_svc_proto_rawDescGZIP(), []int{0}
}

func (x *PurchaseRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PurchaseRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PurchaseResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Status        PurchaseResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=order.PurchaseResponse_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseResponse) Reset() {
	*x = PurchaseResponse{}
	mi := &file_order_svc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseResponse) ProtoMessage() {}

func (x *PurchaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_svc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseResponse.ProtoReflect.Descriptor instead.
func (*PurchaseResponse) Descriptor() ([]byte, []int) {
	return file_order_svc_proto_rawDescGZIP(), []int{1}
}

func (x *PurchaseResponse) GetStatus() PurchaseResponse_Status {
	if x != nil {
		return x.Status
	}
	return PurchaseResponse_QUEUED
}

var File_order_svc_proto protoreflect.FileDescriptor

const file_order_svc_proto_rawDesc = "" +
	"\n" +
	"\x0forder-svc.proto\x12\x05order\"C\n" +
	"\x0fPurchaseRequest\x12\x18\n" +
	"\aeventId\x18\x01 \x01(\tR\aeventId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\"\x9f\x01\n" +
	"\x10PurchaseResponse\x126\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1e.order.PurchaseResponse.StatusR\x06status\"S\n" +
	"\x06Status\x12\n" +
	"\n" +
	"\x06QUEUED\x10\x00\x12\f\n" +
	"\bSOLD_OUT\x10\x01\x12\x14\n" +
	"\x10ALREADY_IN_QUEUE\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\x12\x0e\n" +
	"\n" +
	"QUEUE_FULL\x10\x042Q\n" +
	"\fOrderService\x12A\n" +
	"\x0ePurchaseTicket\x12\x16.order.PurchaseRequest\x1a\x17.order.PurchaseResponseB\x0eZ\forder-svc/pbb\x06proto3"

var (
	file_order_svc_proto_rawDescOnce sync.Once
	file_order_svc_proto_rawDescData []byte
)

func file_order_svc_proto_rawDescGZIP() []byte {
	file_order_svc_proto_rawDescOnce.Do(func() {
		file_order_svc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_svc_proto_rawDesc), len(file_order_svc_proto_rawDesc)))
	})
	return file_order_svc_proto_rawDescData
}

var file_order_svc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_order_svc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_order_svc_proto_goTypes = []any{
	(PurchaseResponse_Status)(0), // 0: order.PurchaseResponse.Status
	(*PurchaseRequest)(nil),      // 1: order.PurchaseRequest
	(*PurchaseResponse)(nil),     // 2: order.PurchaseResponse
}
var file_order_svc_proto_depIdxs = []int32{
	0, // 0: order.PurchaseResponse.status:type_name -> order.PurchaseResponse.Status
	1, // 1: order.OrderService.PurchaseTicket:input_type -> order.PurchaseRequest
	2, // 2: order.OrderService.PurchaseTicket:output_type -> order.PurchaseResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_order_svc_proto_init() }
func file_order_svc_proto_init() {
	if File_order_svc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_svc_proto_rawDesc), len(file_order_svc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_svc_proto_goTypes,
		DependencyIndexes: file_order_svc_proto_depIdxs,
		EnumInfos:         file_order_svc_proto_enumTypes,
		MessageInfos:      file_order_svc_proto_msgTypes,
	}.Build()
	File_order_svc_proto = out.File
	file_order_svc_proto_goTypes = nil
	file_order_svc_proto_depIdxs = nil
}
